name: Exploded View
markdown: kramdown

permalink: pretty
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "git-backup-2018-4-5-20-43", "Gemfile", "Gemfile.lock", "ev2.gemspec"]

twitter_username: explodedviewband
instagram_username: explodedviewband
facebook_username: explodedviewband
github_username:  explodedviewband
soundcloud_username: explodedviewofficial

plugins:
  - jekyll-seo-tag

# Jekyll SEO
title: Exploded View
description: Exploded View is a collaborative project by Anika (Invada Records / Stones Throw), Martin Thulin, Hugo Quezada and Amon Melgarejo.
url: https://explodedview.info
canonical_url: "https://explodedview.info"

twitter:
  username: explodedviewband

facebook:
  publisher: explodedviewband

social:
  name: Exploded View
  links:
    - https://twitter.com/explodedviewband
    - https://www.facebook.com/explodedviewband
    - https://instagram.com/explodedviewband
    - https://soundcloud.com/explodedviewofficial
